//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package mapofsliceskey

import (
	context "context"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*TestStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		return Validate_TestStruct(ctx, op, nil /* fldPath */, obj.(*TestStruct), safe.Cast[*TestStruct](oldObj))
	})
	return nil
}

func Validate_TestStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *TestStruct) (errs field.ErrorList) {
	// type TestStruct
	if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
		return nil // no changes
	}
	errs = append(errs, validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "type TestStruct")...)

	// field TestStruct.TypeMeta has no validation

	// field TestStruct.BasicKeys
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key BasicKeys")
			})...)
			return
		}(fldPath.Child("basicKeys"), obj.BasicKeys, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]string { return oldObj.BasicKeys }))...)

	// field TestStruct.MultipleKeys
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key MultipleKeys #1")
			})...)
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key MultipleKeys #2")
			})...)
			return
		}(fldPath.Child("multipleKeys"), obj.MultipleKeys, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]string { return oldObj.MultipleKeys }))...)

	// field TestStruct.KeysAndSlices
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key KeysAndSlices")
			})...)
			errs = append(errs, validate.EachMapVal(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "slice KeysAndSlices")
			})...)
			return
		}(fldPath.Child("keysAndSlices"), obj.KeysAndSlices, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]string { return oldObj.KeysAndSlices }))...)

	// field TestStruct.KeysAndElements
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key KeysAndElements")
			})...)
			errs = append(errs, validate.EachMapSliceVal(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "element KeysAndElements")
			})...)
			return
		}(fldPath.Child("keysAndElements"), obj.KeysAndElements, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]string { return oldObj.KeysAndElements }))...)

	// field TestStruct.IntSliceKeys
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]int) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key IntSliceKeys")
			})...)
			errs = append(errs, validate.EachMapSliceVal(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *int) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "element IntSliceKeys")
			})...)
			return
		}(fldPath.Child("intSliceKeys"), obj.IntSliceKeys, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]int { return oldObj.IntSliceKeys }))...)

	// field TestStruct.StructSliceKeys
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]User) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key StructSliceKeys")
			})...)
			errs = append(errs, validate.EachMapVal(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []User) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "slice StructSliceKeys")
			})...)
			errs = append(errs, validate.EachMapSliceVal(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *User) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "element StructSliceKeys")
			})...)
			errs = append(errs, validate.EachMapSliceVal(ctx, op, fldPath, obj, oldObj, Validate_User)...)
			return
		}(fldPath.Child("structSliceKeys"), obj.StructSliceKeys, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]User { return oldObj.StructSliceKeys }))...)

	// field TestStruct.TypedefKeys
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string]ValueList) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapKey(ctx, op, fldPath, obj, oldObj, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				return validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "key TypedefKeys")
			})...)
			errs = append(errs, validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "field TestStruct.TypedefKeys")...)
			return
		}(fldPath.Child("typedefKeys"), obj.TypedefKeys, safe.Field(oldObj, func(oldObj *TestStruct) map[string]ValueList { return oldObj.TypedefKeys }))...)

	// field TestStruct.UnvalidatedMap has no validation
	return errs
}

func Validate_User(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *User) (errs field.ErrorList) {
	// type User
	if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
		return nil // no changes
	}
	errs = append(errs, validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "type User")...)

	// field User.Name has no validation
	// field User.ID has no validation
	return errs
}

func Validate_ValueList(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj ValueList) (errs field.ErrorList) {
	// type ValueList
	if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
		return nil // no changes
	}
	errs = append(errs, validate.FixedResult(ctx, op, fldPath, obj, oldObj, false, "type ValueList")...)

	return errs
}
