//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package mode

import (
	context "context"
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	// type ChainedValidation
	scheme.AddValidationFunc((*ChainedValidation)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ChainedValidation(ctx, op, nil /* fldPath */, obj.(*ChainedValidation), safe.Cast[*ChainedValidation](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type ImplicitForbidden
	scheme.AddValidationFunc((*ImplicitForbidden)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ImplicitForbidden(ctx, op, nil /* fldPath */, obj.(*ImplicitForbidden), safe.Cast[*ImplicitForbidden](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type ListTypeInsideMode
	scheme.AddValidationFunc((*ListTypeInsideMode)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ListTypeInsideMode(ctx, op, nil /* fldPath */, obj.(*ListTypeInsideMode), safe.Cast[*ListTypeInsideMode](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type ListTypeSetInsideMode
	scheme.AddValidationFunc((*ListTypeSetInsideMode)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ListTypeSetInsideMode(ctx, op, nil /* fldPath */, obj.(*ListTypeSetInsideMode), safe.Cast[*ListTypeSetInsideMode](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type MultipleDiscriminators
	scheme.AddValidationFunc((*MultipleDiscriminators)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_MultipleDiscriminators(ctx, op, nil /* fldPath */, obj.(*MultipleDiscriminators), safe.Cast[*MultipleDiscriminators](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type NonStringDiscriminator
	scheme.AddValidationFunc((*NonStringDiscriminator)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_NonStringDiscriminator(ctx, op, nil /* fldPath */, obj.(*NonStringDiscriminator), safe.Cast[*NonStringDiscriminator](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type SharedField
	scheme.AddValidationFunc((*SharedField)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_SharedField(ctx, op, nil /* fldPath */, obj.(*SharedField), safe.Cast[*SharedField](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type StrictUnion
	scheme.AddValidationFunc((*StrictUnion)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_StrictUnion(ctx, op, nil /* fldPath */, obj.(*StrictUnion), safe.Cast[*StrictUnion](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

// Validate_ChainedValidation validates an instance of ChainedValidation according
// to declarative validation rules in the API schema.
func Validate_ChainedValidation(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ChainedValidation) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("field"), obj.Field, safe.Field(oldObj, func(oldObj *ChainedValidation) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.Field
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				errs = append(errs, validate.MaxLength(ctx, op, fldPath, obj, oldObj, 5)...)
				return errs
			},
		},
	})...)

	// field ChainedValidation.TypeMeta has no validation
	// field ChainedValidation.Mode has no validation
	// field ChainedValidation.Field has no validation
	return errs
}

// Validate_ImplicitForbidden validates an instance of ImplicitForbidden according
// to declarative validation rules in the API schema.
func Validate_ImplicitForbidden(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ImplicitForbidden) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("field"), obj.Field, safe.Field(oldObj, func(oldObj *ImplicitForbidden) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.Field
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.OptionalPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)

	// field ImplicitForbidden.TypeMeta has no validation
	// field ImplicitForbidden.Mode has no validation
	// field ImplicitForbidden.Field has no validation
	return errs
}

// Validate_ListTypeInsideMode validates an instance of ListTypeInsideMode according
// to declarative validation rules in the API schema.
func Validate_ListTypeInsideMode(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ListTypeInsideMode) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("items"), obj.Items, safe.Field(oldObj, func(oldObj *ListTypeInsideMode) []ListItem {
		if oldObj == nil {
			return nil
		}
		return oldObj.Items
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []ListItem) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenSlice[ListItem](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[[]ListItem]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []ListItem) field.ErrorList {
				errs := field.ErrorList{}
				errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a ListItem, b ListItem) bool { return a.Name == b.Name })...)
				return errs
			},
		},
	})...)

	// field ListTypeInsideMode.TypeMeta has no validation
	// field ListTypeInsideMode.Mode has no validation
	// field ListTypeInsideMode.Items has no validation
	return errs
}

// Validate_ListTypeSetInsideMode validates an instance of ListTypeSetInsideMode according
// to declarative validation rules in the API schema.
func Validate_ListTypeSetInsideMode(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ListTypeSetInsideMode) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("items"), obj.Items, safe.Field(oldObj, func(oldObj *ListTypeSetInsideMode) []string {
		if oldObj == nil {
			return nil
		}
		return oldObj.Items
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenSlice[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[[]string]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj []string) field.ErrorList {
				errs := field.ErrorList{}
				errs = append(errs, validate.Unique(ctx, op, fldPath, obj, oldObj, func(a string, b string) bool { return a == b })...)
				return errs
			},
		},
	})...)

	// field ListTypeSetInsideMode.TypeMeta has no validation
	// field ListTypeSetInsideMode.Mode has no validation
	// field ListTypeSetInsideMode.Items has no validation
	return errs
}

// Validate_MultipleDiscriminators validates an instance of MultipleDiscriminators according
// to declarative validation rules in the API schema.
func Validate_MultipleDiscriminators(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *MultipleDiscriminators) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("ipv6Config"), obj.IPv6Config, safe.Field(oldObj, func(oldObj *MultipleDiscriminators) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.IPv6Config
	}), obj.NetMode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "IPv6",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("s3Bucket"), obj.S3Bucket, safe.Field(oldObj, func(oldObj *MultipleDiscriminators) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.S3Bucket
	}), obj.StorageMode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "S3",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)

	// field MultipleDiscriminators.TypeMeta has no validation
	// field MultipleDiscriminators.NetMode has no validation
	// field MultipleDiscriminators.StorageMode has no validation
	// field MultipleDiscriminators.IPv6Config has no validation
	// field MultipleDiscriminators.S3Bucket has no validation
	return errs
}

// Validate_NonStringDiscriminator validates an instance of NonStringDiscriminator according
// to declarative validation rules in the API schema.
func Validate_NonStringDiscriminator(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *NonStringDiscriminator) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("boolField"), obj.BoolField, safe.Field(oldObj, func(oldObj *NonStringDiscriminator) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.BoolField
	}), obj.BoolMode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "true",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("intField"), obj.IntField, safe.Field(oldObj, func(oldObj *NonStringDiscriminator) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.IntField
	}), obj.IntMode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "1",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)

	// field NonStringDiscriminator.TypeMeta has no validation
	// field NonStringDiscriminator.BoolMode has no validation
	// field NonStringDiscriminator.BoolField has no validation
	// field NonStringDiscriminator.IntMode has no validation
	// field NonStringDiscriminator.IntField has no validation
	return errs
}

// Validate_SharedField validates an instance of SharedField according
// to declarative validation rules in the API schema.
func Validate_SharedField(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *SharedField) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("shared"), obj.Shared, safe.Field(oldObj, func(oldObj *SharedField) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.Shared
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.OptionalPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
		{
			Value: "B",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.OptionalPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)

	// field SharedField.TypeMeta has no validation
	// field SharedField.Mode has no validation
	// field SharedField.Shared has no validation
	return errs
}

// Validate_StrictUnion validates an instance of StrictUnion according
// to declarative validation rules in the API schema.
func Validate_StrictUnion(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *StrictUnion) (errs field.ErrorList) {
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("fieldA"), obj.FieldA, safe.Field(oldObj, func(oldObj *StrictUnion) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.FieldA
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "A",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)
	errs = append(errs, validate.Modal(ctx, op, fldPath, obj, oldObj, fldPath.Child("fieldB"), obj.FieldB, safe.Field(oldObj, func(oldObj *StrictUnion) *string {
		if oldObj == nil {
			return nil
		}
		return oldObj.FieldB
	}), obj.Mode, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
		errs := field.ErrorList{}
		errs = append(errs, validate.ForbiddenPointer[string](ctx, op, fldPath, obj, oldObj)...)
		return errs
	}, []validate.ModalRule[*string]{
		{
			Value: "B",
			Validation: func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *string) field.ErrorList {
				errs := field.ErrorList{}
				earlyReturn := false
				if e := validate.RequiredPointer[string](ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return errs
				}
				return errs
			},
		},
	})...)

	// field StrictUnion.TypeMeta has no validation
	// field StrictUnion.Mode has no validation
	// field StrictUnion.FieldA has no validation
	// field StrictUnion.FieldB has no validation
	return errs
}
