//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package mapofslicespointers

import (
	context "context"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*TestStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		return Validate_TestStruct(ctx, op, nil /* fldPath */, obj.(*TestStruct), safe.Cast[*TestStruct](oldObj))
	})
	return nil
}

func Validate_ComplexStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ComplexStruct) (errs field.ErrorList) {
	// field ComplexStruct.OptionalName has no validation
	// field ComplexStruct.OptionalInt has no validation

	// field ComplexStruct.Nested
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *SimpleStruct) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				return // do not proceed
			}
			errs = append(errs, Validate_SimpleStruct(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("nested"), obj.Nested, safe.Field(oldObj, func(oldObj *ComplexStruct) *SimpleStruct { return oldObj.Nested }))...)

	// field ComplexStruct.Required has no validation
	return errs
}

func Validate_SimpleStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *SimpleStruct) (errs field.ErrorList) {
	// field SimpleStruct.Name
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.MaxLength(ctx, op, fldPath, obj, oldObj, 20)...)
			return
		}(fldPath.Child("name"), &obj.Name, safe.Field(oldObj, func(oldObj *SimpleStruct) *string { return &oldObj.Name }))...)

	// field SimpleStruct.Value
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *int) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			errs = append(errs, validate.Minimum(ctx, op, fldPath, obj, oldObj, 0)...)
			return
		}(fldPath.Child("value"), &obj.Value, safe.Field(oldObj, func(oldObj *SimpleStruct) *int { return &oldObj.Value }))...)

	return errs
}

func Validate_TestStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *TestStruct) (errs field.ErrorList) {
	// field TestStruct.TypeMeta has no validation

	// field TestStruct.StructSlices
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]SimpleStruct) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapVal(ctx, op, fldPath, obj, oldObj,
				func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *[]SimpleStruct) field.ErrorList {
					var errs field.ErrorList
					if obj == nil {
						return nil
					}
					slice := *obj
					var oldSlice []SimpleStruct
					if oldObj != nil {
						oldSlice = *oldObj
					}
					// Element validations
					errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, slice, oldSlice, nil, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *SimpleStruct) field.ErrorList {
						return Validate_SimpleStruct(ctx, op, fldPath, obj, oldObj)
					})...)
					return errs
				})...)
			return
		}(fldPath.Child("structSlices"), obj.StructSlices, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]SimpleStruct { return oldObj.StructSlices }))...)

	// field TestStruct.ComplexStructSlices
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string][]ComplexStruct) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			errs = append(errs, validate.EachMapVal(ctx, op, fldPath, obj, oldObj,
				func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *[]ComplexStruct) field.ErrorList {
					var errs field.ErrorList
					if obj == nil {
						return nil
					}
					slice := *obj
					var oldSlice []ComplexStruct
					if oldObj != nil {
						oldSlice = *oldObj
					}
					// Element validations
					errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, slice, oldSlice, nil, func(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ComplexStruct) field.ErrorList {
						return Validate_ComplexStruct(ctx, op, fldPath, obj, oldObj)
					})...)
					return errs
				})...)
			return
		}(fldPath.Child("complexStructSlices"), obj.ComplexStructSlices, safe.Field(oldObj, func(oldObj *TestStruct) map[string][]ComplexStruct { return oldObj.ComplexStructSlices }))...)

	// field TestStruct.StringSlices has no validation
	return errs
}
