//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package update

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*UpdateTestStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_UpdateTestStruct(ctx, op, nil /* fldPath */, obj.(*UpdateTestStruct), safe.Cast[*UpdateTestStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

func Validate_UpdateTestStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *UpdateTestStruct) (errs field.ErrorList) {
	// field UpdateTestStruct.TypeMeta has no validation

	// field UpdateTestStruct.SetOnceField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("setOnceField"), &obj.SetOnceField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.SetOnceField }))...)

	// field UpdateTestStruct.CreateOnlyField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("createOnlyField"), &obj.CreateOnlyField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.CreateOnlyField }))...)

	// field UpdateTestStruct.AppendOnlyList
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalSlice(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoRemoveItem(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("appendOnlyList"), obj.AppendOnlyList, safe.Field(oldObj, func(oldObj *UpdateTestStruct) []string { return oldObj.AppendOnlyList }))...)

	// field UpdateTestStruct.ImmutableList
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []Item) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalSlice(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoAddItem(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoRemoveItem(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("immutableList"), obj.ImmutableList, safe.Field(oldObj, func(oldObj *UpdateTestStruct) []Item { return oldObj.ImmutableList }))...)

	// field UpdateTestStruct.NoRemoveMap
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalMap(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoRemoveItemMap(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("noRemoveMap"), obj.NoRemoveMap, safe.Field(oldObj, func(oldObj *UpdateTestStruct) map[string]string { return oldObj.NoRemoveMap }))...)

	// field UpdateTestStruct.RequiredOnceSetField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("requiredOnceSetField"), obj.RequiredOnceSetField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.RequiredOnceSetField }))...)

	// field UpdateTestStruct.TrulyImmutableField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.ImmutableByCompare(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("trulyImmutableField"), &obj.TrulyImmutableField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.TrulyImmutableField }))...)

	// field UpdateTestStruct.RequiredImmutableField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.ImmutableByCompare(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("requiredImmutableField"), &obj.RequiredImmutableField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.RequiredImmutableField }))...)

	return errs
}
