//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package update

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	scheme.AddValidationFunc((*UpdateTestStruct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_UpdateTestStruct(ctx, op, nil /* fldPath */, obj.(*UpdateTestStruct), safe.Cast[*UpdateTestStruct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

func Validate_UpdateTestStruct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *UpdateTestStruct) (errs field.ErrorList) {
	// field UpdateTestStruct.TypeMeta has no validation

	// field UpdateTestStruct.PrimitiveNoSet
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveNoSet"), &obj.PrimitiveNoSet, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveNoSet }))...)

	// field UpdateTestStruct.PrimitiveNoUnset
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveNoUnset"), &obj.PrimitiveNoUnset, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveNoUnset }))...)

	// field UpdateTestStruct.PrimitiveNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveNoModify"), &obj.PrimitiveNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveNoModify }))...)

	// field UpdateTestStruct.PrimitiveFullyRestricted
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveFullyRestricted"), &obj.PrimitiveFullyRestricted, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveFullyRestricted }))...)

	// field UpdateTestStruct.PrimitiveRequiredNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveRequiredNoModify"), &obj.PrimitiveRequiredNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveRequiredNoModify }))...)

	// field UpdateTestStruct.PrimitiveSetOnce
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("primitiveSetOnce"), &obj.PrimitiveSetOnce, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.PrimitiveSetOnce }))...)

	// field UpdateTestStruct.IntNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *int) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("intNoModify"), &obj.IntNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *int { return &oldObj.IntNoModify }))...)

	// field UpdateTestStruct.BoolNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *bool) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("boolNoModify"), &obj.BoolNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *bool { return &oldObj.BoolNoModify }))...)

	// field UpdateTestStruct.Float64NoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *float64) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("float64NoModify"), &obj.Float64NoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *float64 { return &oldObj.Float64NoModify }))...)

	// field UpdateTestStruct.OptionalDefaultNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultNoModify"), &obj.OptionalDefaultNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.OptionalDefaultNoModify }))...)

	// field UpdateTestStruct.OptionalDefaultNoSet
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultNoSet"), &obj.OptionalDefaultNoSet, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.OptionalDefaultNoSet }))...)

	// field UpdateTestStruct.OptionalDefaultNoUnset
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultNoUnset"), &obj.OptionalDefaultNoUnset, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return &oldObj.OptionalDefaultNoUnset }))...)

	// field UpdateTestStruct.OptionalDefaultIntNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *int) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultIntNoModify"), &obj.OptionalDefaultIntNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *int { return &oldObj.OptionalDefaultIntNoModify }))...)

	// field UpdateTestStruct.OptionalDefaultBoolNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *bool) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultBoolNoModify"), &obj.OptionalDefaultBoolNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *bool { return &oldObj.OptionalDefaultBoolNoModify }))...)

	// field UpdateTestStruct.StructNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *TestStruct) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("structNoModify"), &obj.StructNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *TestStruct { return &oldObj.StructNoModify }))...)

	// field UpdateTestStruct.PointerNoSet
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("pointerNoSet"), obj.PointerNoSet, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.PointerNoSet }))...)

	// field UpdateTestStruct.PointerNoUnset
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("pointerNoUnset"), obj.PointerNoUnset, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.PointerNoUnset }))...)

	// field UpdateTestStruct.PointerNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("pointerNoModify"), obj.PointerNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.PointerNoModify }))...)

	// field UpdateTestStruct.PointerFullyRestricted
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("pointerFullyRestricted"), obj.PointerFullyRestricted, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.PointerFullyRestricted }))...)

	// field UpdateTestStruct.OptionalDefaultPointerNoModify
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string) (errs field.ErrorList) {
			if op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil // no changes
			}
			{
				earlyReturn := false
				// optional fields with default values are effectively required
				if e := validate.RequiredPointer(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoSet(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoUnset(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if e := validate.NoModify(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					errs = append(errs, e...)
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("optionalDefaultPointerNoModify"), obj.OptionalDefaultPointerNoModify, safe.Field(oldObj, func(oldObj *UpdateTestStruct) *string { return oldObj.OptionalDefaultPointerNoModify }))...)

	// field UpdateTestStruct.ListField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalSlice(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("listField"), obj.ListField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) []string { return oldObj.ListField }))...)

	// field UpdateTestStruct.MapField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj map[string]string) (errs field.ErrorList) {
			if op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil // no changes
			}
			{
				earlyReturn := false
				if e := validate.OptionalMap(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
					earlyReturn = true
				}
				if earlyReturn {
					return // do not proceed
				}
			}
			return
		}(fldPath.Child("mapField"), obj.MapField, safe.Field(oldObj, func(oldObj *UpdateTestStruct) map[string]string { return oldObj.MapField }))...)

	return errs
}
